In [1]:
import cv2
import numpy as np
import tensorflow as tf
import os

from tensorflow.keras.models import load_model

2025-01-30 14:58:45.567199: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-01-30 14:58:45.707820: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-01-30 14:58:45.707893: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-01-30 14:58:45.728448: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-30 14:58:45.776292: I tensorflow/core/platform/cpu_feature_guar

In [2]:
# model = tf.keras.applications.efficientnet_v2.EfficientNetV2S()

In [3]:
model_dir = "/home/abhinav/Documents/Work/2 Hobby_projects/Models"

path_to_saved_arch = os.path.join(model_dir, "Mynet_beetles_7")


In [4]:
model = load_model(path_to_saved_arch)

2025-01-30 14:58:47.543315: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-01-30 14:58:47.660398: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-01-30 14:58:47.660546: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-

In [5]:
# class_names = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"]

class_names = ["1", "2", "3", "4"]


In [ ]:
# importing the necessary libraries
import cv2
import numpy as np

# Creating a VideoCapture object to read the video
cap = cv2.VideoCapture(0)


# Loop until the end of the video
while (cap.isOpened()):

    # Capture frame-by-frame
    ret, frame = cap.read()
    frame = cv2.resize(frame, (456, 356), fx = 0, fy = 0,
                         interpolation = cv2.INTER_CUBIC)

    # Display the resulting frame
    
    frame = cv2.flip(frame, 1)
    nframe = tf.image.resize(frame, [140, 140])
    
    nframe = tf.expand_dims(nframe, 0)
    # conversion of BGR to grayscale is necessary to apply this operation
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # adaptive thresholding to use different threshold 

    Thresh = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_MEAN_C,
                                           cv2.THRESH_BINARY_INV, 11, 2)
    prediction = model.predict(nframe)
    print("Shape of prediction")
    print(prediction)
    prediction_values = np.argmax(prediction, axis=-1)
    print("Shape of prediction_Values: ", prediction_values.shape)
    print("prediction values: ", prediction_values)
    # c = []
    # for i in prediction_values:
    #     c.append(class_names[i])
    # print(c)

    # prediction_act_values = c[0]
    # print(prediction_act_values)
    if prediction_values[0] == 2:
        cv2.putText(frame,"Beetle Detected",(50,50),cv2.FONT_HERSHEY_COMPLEX_SMALL,2,(100,0,255))
    else:
        cv2.putText(frame, str(""),(50,50),cv2.FONT_HERSHEY_COMPLEX_SMALL,2,(100,0,255))

    cv2.imshow('Frame', frame)
    # cv2.imshow('Thresh', Thresh)
    # cv2.imshow(prediction_act_values, Thresh)
    # define q as the exit button
    if cv2.waitKey(25) & 0xFF == ord('q'):
        break

# release the video capture object
cap.release()
# Closes all the windows currently opened.
cv2.destroyAllWindows()

2025-01-30 14:58:48.880684: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:454] Loaded cuDNN version 8907
2025-01-30 14:58:48.991170: I external/local_tsl/tsl/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory


1/1 [==============================] - 2s 2s/step


2025-01-30 14:58:50.353557: I external/local_tsl/tsl/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory


Shape of prediction
[[0.0000000e+00 0.0000000e+00 4.2461822e-11 1.0000000e+00]]
Shape of prediction_Values:  (1,)
prediction values:  [3]
1/1 [==============================] - 0s 14ms/step
Shape of prediction
[[0.0000000e+00 0.0000000e+00 2.0796664e-09 1.0000000e+00]]
Shape of prediction_Values:  (1,)
prediction values:  [3]
1/1 [==============================] - 0s 15ms/step
Shape of prediction
[[0.0000000e+00 0.0000000e+00 2.2965077e-09 1.0000000e+00]]
Shape of prediction_Values:  (1,)
prediction values:  [3]
1/1 [==============================] - 0s 13ms/step
Shape of prediction
[[0.0000000e+00 0.0000000e+00 1.9785594e-08 1.0000000e+00]]
Shape of prediction_Values:  (1,)
prediction values:  [3]
1/1 [==============================] - 0s 13ms/step
Shape of prediction
[[0.000000e+00 0.000000e+00 4.908968e-09 1.000000e+00]]
Shape of prediction_Values:  (1,)
prediction values:  [3]
1/1 [==============================] - 0s 13ms/step
Shape of prediction
[[0.         0.         0.93678206

In [ ]:

# cap = cv2.VideoCapture(0)

# while True:
#     _, frame = cap.read()
#     if frame is None:
#         break
    
#     nframe = tf.image.resize(frame, [128, 128])
#     nframe = tf.expand_dims(nframe, 0)
#     prediction = model.predict(nframe)

#     cv2.imshow(str(prediction), frame)

#     # To quit the capturing
#     if cv2.waitKey(1) & 0xFF == ord("q"):
#         break
#     break

# cap.release()
# cv2.destroyAllWindows()