In [110]:
import torch
import numpy as np

In [111]:
# Initializing a tensor

# Directly from data

data = [[1, 2, 3, 4], [5, 6, 7, 8]]
x_data = torch.tensor(data)

print("Tensor from data:", x_data)

Tensor from data: tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [112]:
# From a numpy array

np_data = np.array(data)
np_data = torch.from_numpy(np_data)

print("Tensor from np array: ", np_data)

Tensor from np array:  tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [113]:
x_ones = torch.ones_like(x_data)                      # Retains the structure of x_data
print(f"Tensor created from a previous tensor with all values as one: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=float)         # Overrides the dtype of x_data
print(f"Tensor created from a previous tensor with random values: \n {x_rand} \n")

Tensor created from a previous tensor with all values as one: 
 tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]]) 

Tensor created from a previous tensor with random values: 
 tensor([[0.9861, 0.2013, 0.6748, 0.8993],
        [0.0785, 0.8546, 0.9484, 0.3654]], dtype=torch.float64) 



In [114]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape, dtype=int)
zeros_tensor = torch.zeros(shape)

print(f"rand tensor: \n {rand_tensor} \n")
print(f"ones tensor: \n {ones_tensor} \n")
print(f"zeros tensor: \n {zeros_tensor} \n")

rand tensor: 
 tensor([[0.4979, 0.0316, 0.9400],
        [0.4695, 0.0048, 0.4237]]) 

ones tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1]]) 

zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [115]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape, dtype=int)
zeros_tensor = torch.zeros(shape)

print(f"rand tensor: \n {rand_tensor} \n")
print(f"ones tensor: \n {ones_tensor} \n")
print(f"zeros tensor: \n {zeros_tensor} \n")

rand tensor: 
 tensor([[0.5849, 0.5748, 0.6566],
        [0.1519, 0.1587, 0.9133]]) 

ones tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1]]) 

zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [116]:
# Attributs of a tensor

att_tensor = torch.rand((2, 3))

print("shape of tensor: ", att_tensor.shape)
print("dtype of tensor: ", att_tensor.dtype)
print("device on of tenosr: ", att_tensor.device)

shape of tensor:  torch.Size([2, 3])
dtype of tensor:  torch.float32
device on of tenosr:  cpu


In [117]:
att_tensor = torch.rand(2, 3)

print("shape of tensor: ", att_tensor.shape)
print("dtype of tensor: ", att_tensor.dtype)
print("device on of tenosr: ", att_tensor.device)

shape of tensor:  torch.Size([2, 3])
dtype of tensor:  torch.float32
device on of tenosr:  cpu


In [118]:
if torch.cuda.is_available():
    att_tensor = att_tensor.to("cuda")

In [119]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("tensor: ", tensor)
print(f"First row: \n {tensor[0]} \n")
print(f"First column: \n {tensor[:, 0]} \n")
print(f"Last column: \n {tensor[..., -1]} \n")
print("Second way of printing last coloumn: ", tensor[..., -1])

tensor:  tensor([[1, 2, 3],
        [4, 5, 6]])
First row: 
 tensor([1, 2, 3]) 

First column: 
 tensor([1, 4]) 

Last column: 
 tensor([3, 6]) 

Second way of printing last coloumn:  tensor([3, 6])


In [120]:
join_tensor = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])

join_tensor

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [121]:
joined_tensor = torch.cat([join_tensor, join_tensor, join_tensor], dim=1)

joined_tensor

tensor([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
        [5, 6, 7, 8, 5, 6, 7, 8, 5, 6, 7, 8]])

In [122]:
joined_tensor1 = torch.cat([join_tensor, join_tensor, join_tensor], dim=0)


joined_tensor1

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [1, 2, 3, 4],
        [5, 6, 7, 8]])

In [123]:
# To perform matrix multiplication

tensor = torch.ones(4, 4)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

print(f"Y1: \n {y1} \n")
print(f"Y2: \n {y2} \n")
print(f"Y3: \n {y3} \n")

Y1: 
 tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]) 

Y2: 
 tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]) 

Y3: 
 tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]) 



In [124]:
# To perform element wise multiplication

z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(z1)
torch.mul(tensor, tensor, out=z3)

print(f"z1: \n {z1} \n")
print(f"z2: \n {z2} \n")
print(f"z3: \n {z3} \n")

z1: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

z2: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

z3: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 



In [125]:
agg = tensor.sum()
agg_item = agg.item()

print(f"agg item is: {agg_item} and its type is: {type(agg_item)}")

agg item is: 16.0 and its type is: <class 'float'>


In [126]:
# in-place addition operation

print(tensor)

tensor.add_(5)

print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


In [127]:
t = torch.ones(4)
print("tensor: ", t)
n = t.numpy()
print("numpy: ", n)

tensor:  tensor([1., 1., 1., 1.])
numpy:  [1. 1. 1. 1.]


In [128]:
t.add_(5)
print("tensor: ", t)
print("numpy: ", n)

tensor:  tensor([6., 6., 6., 6.])
numpy:  [6. 6. 6. 6.]


In [129]:
nu = np.ones(5)
te = torch.from_numpy(nu)
print("numpy: ", nu)
print("tensor: ", te)

numpy:  [1. 1. 1. 1. 1.]
tensor:  tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [130]:
np.add(nu, 1, out=nu)
print("numpy: ", nu)
print("tensor: ", te)

numpy:  [2. 2. 2. 2. 2.]
tensor:  tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [131]:
src = torch.arange(1, 16).reshape((3, 5, ))

src

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]])

In [132]:
idx = torch.tensor([[0, 1, 2]])

idx

tensor([[0, 1, 2]])

In [133]:
st = torch.zeros(3, 5, dtype=src.dtype)

st

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [134]:
st.scatter_(0, idx, src)

tensor([[1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0]])

In [135]:
st.scatter_(1, idx, src)

tensor([[1, 2, 3, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0]])

In [136]:
idx2 = torch.tensor([[0, 1, 2], [1, 2, 3], [2, 3, 4]])

idx2

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])

In [137]:
st.scatter_(1, idx2, src)

tensor([[ 1,  2,  3,  0,  0],
        [ 0,  6,  7,  8,  0],
        [ 0,  0, 11, 12, 13]])

In [138]:
p = torch.arange(1, 11).reshape(2, 5)
q = torch.tensor([[0, 1]])
print(p)
print(q)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
tensor([[0, 1]])


In [139]:
s = torch.zeros(2, 5, dtype=p.dtype)

s

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [140]:
s.scatter_(0, q, p)

tensor([[1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0]])

In [141]:
y = torch.tensor([ [4, 3, 5, 2, 3], [7, 6, 4, 7, 5], [6, 9, 0, 5, 7], [4, 6, 5, 8, 3], [2, 4, 3, 7, 5] ])
i = torch.tensor([ [0, 1, 2, 1, 0], [1, 2, 3, 2, 1] ])
g = torch.zeros(5, 5, dtype=y.dtype).scatter_(0, i, y)

g

tensor([[4, 0, 0, 0, 3],
        [7, 3, 0, 2, 5],
        [0, 6, 5, 7, 0],
        [0, 0, 4, 0, 0],
        [0, 0, 0, 0, 0]])

In [142]:
y = torch.tensor([ [4, 3, 5, 2, 3], [7, 6, 4, 7, 5], [6, 9, 0, 5, 7], [4, 6, 5, 8, 3], [2, 4, 3, 7, 5] ])
i = torch.tensor([ [0, 1, 2, 3, 4], [4, 3, 2, 1, 0], [2, 3, 1, 0, 4] ])
g = torch.zeros(5, 5, dtype=y.dtype).scatter_(1, i, y)

g

tensor([[4, 3, 5, 2, 3],
        [5, 7, 4, 6, 7],
        [5, 0, 6, 9, 7],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [143]:
src = torch.arange(100, 130).reshape(5, 6)
indx = torch.tensor([ [1], [2], [3], [4], [5] ])
srcout = torch.zeros(5, 6, dtype=src.dtype).scatter_(1, indx, src)

srcout

tensor([[  0, 100,   0,   0,   0,   0],
        [  0,   0, 106,   0,   0,   0],
        [  0,   0,   0, 112,   0,   0],
        [  0,   0,   0,   0, 118,   0],
        [  0,   0,   0,   0,   0, 124]])

In [147]:
src = torch.zeros(10)
indx = torch.tensor([5])
srcout = torch.zeros(10, dtype=src.dtype).scatter_(0, indx, value=1)

srcout

tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])