In [2]:
import torch
import numpy as np

In [3]:
# Initializing a tensor

# Directly from data

data = [[1, 2, 3, 4], [5, 6, 7, 8]]
x_data = torch.tensor(data)

print("Tensor from data:", x_data)

Tensor from data: tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [4]:
# From a numpy array

np_data = np.array(data)
np_data = torch.from_numpy(np_data)

print("Tensor from np array: ", np_data)

Tensor from np array:  tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [5]:
x_ones = torch.ones_like(x_data)                      # Retains the structure of x_data
print(f"Tensor created from a previous tensor with all values as one: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=float)         # Overrides the dtype of x_data
print(f"Tensor created from a previous tensor with random values: \n {x_rand} \n")

Tensor created from a previous tensor with all values as one: 
 tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]]) 

Tensor created from a previous tensor with random values: 
 tensor([[0.6212, 0.6461, 0.9722, 0.3583],
        [0.7334, 0.3278, 0.4397, 0.3348]], dtype=torch.float64) 



In [6]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape, dtype=int)
zeros_tensor = torch.zeros(shape)

print(f"rand tensor: \n {rand_tensor} \n")
print(f"ones tensor: \n {ones_tensor} \n")
print(f"zeros tensor: \n {zeros_tensor} \n")

rand tensor: 
 tensor([[0.8358, 0.9217, 0.7929],
        [0.5806, 0.5936, 0.4244]]) 

ones tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1]]) 

zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [7]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape, dtype=int)
zeros_tensor = torch.zeros(shape)

print(f"rand tensor: \n {rand_tensor} \n")
print(f"ones tensor: \n {ones_tensor} \n")
print(f"zeros tensor: \n {zeros_tensor} \n")

rand tensor: 
 tensor([[0.8097, 0.3604, 0.2458],
        [0.6434, 0.0731, 0.0381]]) 

ones tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1]]) 

zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [8]:
# Attributs of a tensor

att_tensor = torch.rand((2, 3))

print("shape of tensor: ", att_tensor.shape)
print("dtype of tensor: ", att_tensor.dtype)
print("device on of tenosr: ", att_tensor.device)

shape of tensor:  torch.Size([2, 3])
dtype of tensor:  torch.float32
device on of tenosr:  cpu


In [9]:
att_tensor = torch.rand(2, 3)

print("shape of tensor: ", att_tensor.shape)
print("dtype of tensor: ", att_tensor.dtype)
print("device on of tenosr: ", att_tensor.device)

shape of tensor:  torch.Size([2, 3])
dtype of tensor:  torch.float32
device on of tenosr:  cpu


In [10]:
if torch.cuda.is_available():
    att_tensor = att_tensor.to("cuda")

In [11]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("tensor: ", tensor)
print(f"First row: \n {tensor[0]} \n")
print(f"First column: \n {tensor[:, 0]} \n")
print(f"Last column: \n {tensor[..., -1]} \n")
print("Second way of printing last coloumn: ", tensor[..., -1])

tensor:  tensor([[1, 2, 3],
        [4, 5, 6]])
First row: 
 tensor([1, 2, 3]) 

First column: 
 tensor([1, 4]) 

Last column: 
 tensor([3, 6]) 

Second way of printing last coloumn:  tensor([3, 6])


In [12]:
join_tensor = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])

join_tensor

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [13]:
joined_tensor = torch.cat([join_tensor, join_tensor, join_tensor], dim=1)

joined_tensor

tensor([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
        [5, 6, 7, 8, 5, 6, 7, 8, 5, 6, 7, 8]])

In [14]:
joined_tensor1 = torch.cat([join_tensor, join_tensor, join_tensor], dim=0)


joined_tensor1

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [1, 2, 3, 4],
        [5, 6, 7, 8]])

In [15]:
# To perform matrix multiplication

tensor = torch.ones(4, 4)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

print(f"Y1: \n {y1} \n")
print(f"Y2: \n {y2} \n")
print(f"Y3: \n {y3} \n")

Y1: 
 tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]) 

Y2: 
 tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]) 

Y3: 
 tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]) 



In [16]:
# To perform element wise multiplication

z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(z1)
torch.mul(tensor, tensor, out=z3)

print(f"z1: \n {z1} \n")
print(f"z2: \n {z2} \n")
print(f"z3: \n {z3} \n")

z1: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

z2: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

z3: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 



In [17]:
agg = tensor.sum()
agg_item = agg.item()

print(f"agg item is: {agg_item} and its type is: {type(agg_item)}")

agg item is: 16.0 and its type is: <class 'float'>


In [18]:
# in-place addition operation

print(tensor)

tensor.add_(5)

print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


In [19]:
t = torch.ones(4)
print("tensor: ", t)
n = t.numpy()
print("numpy: ", n)

tensor:  tensor([1., 1., 1., 1.])
numpy:  [1. 1. 1. 1.]


In [20]:
t.add_(5)
print("tensor: ", t)
print("numpy: ", n)

tensor:  tensor([6., 6., 6., 6.])
numpy:  [6. 6. 6. 6.]


In [21]:
nu = np.ones(5)
te = torch.from_numpy(nu)
print("numpy: ", nu)
print("tensor: ", te)

numpy:  [1. 1. 1. 1. 1.]
tensor:  tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [22]:
np.add(nu, 1, out=nu)
print("numpy: ", nu)
print("tensor: ", te)

numpy:  [2. 2. 2. 2. 2.]
tensor:  tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [23]:
src = torch.arange(1, 16).reshape((3, 5, ))

src

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]])

In [24]:
idx = torch.tensor([[0, 1, 2]])

idx

tensor([[0, 1, 2]])

In [25]:
st = torch.zeros(3, 5, dtype=src.dtype)

st

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [26]:
st.scatter_(0, idx, src)

tensor([[1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0]])

In [27]:
st.scatter_(1, idx, src)

tensor([[1, 2, 3, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0]])

In [28]:
idx2 = torch.tensor([[0, 1, 2], [1, 2, 3], [2, 3, 4]])

idx2

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])

In [29]:
st.scatter_(1, idx2, src)

tensor([[ 1,  2,  3,  0,  0],
        [ 0,  6,  7,  8,  0],
        [ 0,  0, 11, 12, 13]])

In [30]:
p = torch.arange(1, 11).reshape(2, 5)
q = torch.tensor([[0, 1]])
print(p)
print(q)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
tensor([[0, 1]])


In [31]:
s = torch.zeros(2, 5, dtype=p.dtype)

s

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [32]:
s.scatter_(0, q, p)

tensor([[1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0]])

In [33]:
y = torch.tensor([ [4, 3, 5, 2, 3], [7, 6, 4, 7, 5], [6, 9, 0, 5, 7], [4, 6, 5, 8, 3], [2, 4, 3, 7, 5] ])
i = torch.tensor([ [0, 1, 2, 1, 0], [1, 2, 3, 2, 1] ])
g = torch.zeros(5, 5, dtype=y.dtype).scatter_(0, i, y)

g

tensor([[4, 0, 0, 0, 3],
        [7, 3, 0, 2, 5],
        [0, 6, 5, 7, 0],
        [0, 0, 4, 0, 0],
        [0, 0, 0, 0, 0]])

In [34]:
y = torch.tensor([ [4, 3, 5, 2, 3], [7, 6, 4, 7, 5], [6, 9, 0, 5, 7], [4, 6, 5, 8, 3], [2, 4, 3, 7, 5] ])
i = torch.tensor([ [0, 1, 2, 3, 4], [4, 3, 2, 1, 0], [2, 3, 1, 0, 4] ])
g = torch.zeros(5, 5, dtype=y.dtype).scatter_(1, i, y)

g

tensor([[4, 3, 5, 2, 3],
        [5, 7, 4, 6, 7],
        [5, 0, 6, 9, 7],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [35]:
src = torch.arange(100, 130).reshape(5, 6)
indx = torch.tensor([ [1], [2], [3], [4], [5] ])
srcout = torch.zeros(5, 6, dtype=src.dtype).scatter_(1, indx, src)

srcout

tensor([[  0, 100,   0,   0,   0,   0],
        [  0,   0, 106,   0,   0,   0],
        [  0,   0,   0, 112,   0,   0],
        [  0,   0,   0,   0, 118,   0],
        [  0,   0,   0,   0,   0, 124]])

In [36]:
src = torch.zeros(10)
indx = torch.tensor([5])
srcout = torch.zeros(10, dtype=src.dtype).scatter_(0, indx, value=1)

srcout

tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [37]:
x = torch.ones(5)
y = torch.zeros(3)

print("Input: ", x)
print("Expected output: ", y)

Input:  tensor([1., 1., 1., 1., 1.])
Expected output:  tensor([0., 0., 0.])


In [42]:
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)

z = torch.matmul(x, w) + b

loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [44]:
print("weights: ", w)
print("\nbias: ", b)

print("\nz: ", z)
print("\nloss: ", loss)

weights:  tensor([[-1.1845e+00, -4.8193e-01,  7.0581e-04],
        [ 2.1177e-01,  1.7791e+00,  2.7063e-01],
        [-1.6361e+00, -1.5310e+00, -1.7240e+00],
        [-4.4995e-01, -7.8874e-02, -8.1305e-01],
        [-1.5742e+00, -2.7898e-02,  1.1898e+00]], requires_grad=True)

bias:  tensor([ 0.2205, -0.3941,  1.8157], requires_grad=True)

z:  tensor([-4.4124, -0.7346,  0.7398], grad_fn=<AddBackward0>)

loss:  tensor(0.5113, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [45]:
print(f"Gradient function for z: {z.grad_fn}")
print(f"Gradient function for loss: {loss.grad_fn}")

Gradient function for z: <AddBackward0 object at 0x7fd1e42c68f0>
Gradient function for loss: <BinaryCrossEntropyWithLogitsBackward0 object at 0x7fd1e42c7c40>


In [48]:
loss.backward()

print("Gradients of parameter set w: ", w.grad)
print("\n Gradients of parameter set b: ", b.grad)

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.