In [1]:
import torch
import numpy as np

In [2]:
# Initializing a tensor

# Directly from data

data = [[1, 2, 3, 4], [5, 6, 7, 8]]
x_data = torch.tensor(data)

print("Tensor from data:", x_data)

Tensor from data: tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [3]:
# From a numpy array

np_data = np.array(data)
np_data = torch.from_numpy(np_data)

print("Tensor from np array: ", np_data)

Tensor from np array:  tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [4]:
x_ones = torch.ones_like(x_data)                      # Retains the structure of x_data
print(f"Tensor created from a previous tensor with all values as one: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=float)         # Overrides the dtype of x_data
print(f"Tensor created from a previous tensor with random values: \n {x_rand} \n")

Tensor created from a previous tensor with all values as one: 
 tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]]) 

Tensor created from a previous tensor with random values: 
 tensor([[0.4567, 0.6357, 0.8227, 0.7582],
        [0.6050, 0.0130, 0.4055, 0.1570]], dtype=torch.float64) 



In [5]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape, dtype=int)
zeros_tensor = torch.zeros(shape)

print(f"rand tensor: \n {rand_tensor} \n")
print(f"ones tensor: \n {ones_tensor} \n")
print(f"zeros tensor: \n {zeros_tensor} \n")

rand tensor: 
 tensor([[0.2114, 0.9326, 0.5419],
        [0.9482, 0.8380, 0.3657]]) 

ones tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1]]) 

zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [6]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape, dtype=int)
zeros_tensor = torch.zeros(shape)

print(f"rand tensor: \n {rand_tensor} \n")
print(f"ones tensor: \n {ones_tensor} \n")
print(f"zeros tensor: \n {zeros_tensor} \n")

rand tensor: 
 tensor([[0.2991, 0.2827, 0.2872],
        [0.6912, 0.8000, 0.3126]]) 

ones tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1]]) 

zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [7]:
# Attributs of a tensor

att_tensor = torch.rand((2, 3))

print("shape of tensor: ", att_tensor.shape)
print("dtype of tensor: ", att_tensor.dtype)
print("device on of tenosr: ", att_tensor.device)

shape of tensor:  torch.Size([2, 3])
dtype of tensor:  torch.float32
device on of tenosr:  cpu


In [8]:
att_tensor = torch.rand(2, 3)

print("shape of tensor: ", att_tensor.shape)
print("dtype of tensor: ", att_tensor.dtype)
print("device on of tenosr: ", att_tensor.device)

shape of tensor:  torch.Size([2, 3])
dtype of tensor:  torch.float32
device on of tenosr:  cpu


In [9]:
if torch.cuda.is_available():
    att_tensor = att_tensor.to("cuda")

/home/abhinav/.local/lib/python3.10/site-packages/torch/cuda/__init__.py:128: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0


In [10]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("tensor: ", tensor)
print(f"First row: \n {tensor[0]} \n")
print(f"First column: \n {tensor[:, 0]} \n")
print(f"Last column: \n {tensor[..., -1]} \n")
print("Second way of printing last coloumn: ", tensor[..., -1])

tensor:  tensor([[1, 2, 3],
        [4, 5, 6]])
First row: 
 tensor([1, 2, 3]) 

First column: 
 tensor([1, 4]) 

Last column: 
 tensor([3, 6]) 

Second way of printing last coloumn:  tensor([3, 6])


In [11]:
join_tensor = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])

join_tensor

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [12]:
joined_tensor = torch.cat([join_tensor, join_tensor, join_tensor], dim=1)

joined_tensor

tensor([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
        [5, 6, 7, 8, 5, 6, 7, 8, 5, 6, 7, 8]])

In [13]:
joined_tensor1 = torch.cat([join_tensor, join_tensor, join_tensor], dim=0)


joined_tensor1

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [1, 2, 3, 4],
        [5, 6, 7, 8]])

In [14]:
# To perform matrix multiplication

tensor = torch.ones(4, 4)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

print(f"Y1: \n {y1} \n")
print(f"Y2: \n {y2} \n")
print(f"Y3: \n {y3} \n")

Y1: 
 tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]) 

Y2: 
 tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]) 

Y3: 
 tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]) 



In [15]:
# To perform element wise multiplication

z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(z1)
torch.mul(tensor, tensor, out=z3)

print(f"z1: \n {z1} \n")
print(f"z2: \n {z2} \n")
print(f"z3: \n {z3} \n")

z1: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

z2: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

z3: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 



In [16]:
agg = tensor.sum()
agg_item = agg.item()

print(f"agg item is: {agg_item} and its type is: {type(agg_item)}")

agg item is: 16.0 and its type is: <class 'float'>


In [17]:
# in-place addition operation

print(tensor)

tensor.add_(5)

print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


In [18]:
t = torch.ones(4)
print("tensor: ", t)
n = t.numpy()
print("numpy: ", n)

tensor:  tensor([1., 1., 1., 1.])
numpy:  [1. 1. 1. 1.]


In [19]:
t.add_(5)
print("tensor: ", t)
print("numpy: ", n)

tensor:  tensor([6., 6., 6., 6.])
numpy:  [6. 6. 6. 6.]


In [20]:
nu = np.ones(5)
te = torch.from_numpy(nu)
print("numpy: ", nu)
print("tensor: ", te)

numpy:  [1. 1. 1. 1. 1.]
tensor:  tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [21]:
np.add(nu, 1, out=nu)
print("numpy: ", nu)
print("tensor: ", te)

numpy:  [2. 2. 2. 2. 2.]
tensor:  tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
